<a href="https://colab.research.google.com/github/lava99-bliss/AS2019364/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#tensors udsing tensorflow


*   Intro to tensors
*   Getting info from tensors
*   Manipulating tensors
*   Tensors and Numpy
*   Using @tf.function(way to speed up regular Py function)
*   Using GPUs with tensorflow(or TPUs)
*   Excercises







##Intro to tensors

In [1]:
#import tensor
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#create tensor using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimentions of a tensor (ndim-no of dims)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dim of vector
vector.ndim

1

In [6]:
#create a matrix (has more than 1 dims)
matrix = tf.constant(([10,7],
                     [7,10]))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10.,7.],
                     [7.,10.],
                     [7.,10.]], dtype=tf.float16) #specify data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 7., 10.]], dtype=float16)>

In [9]:
 tensor = tf.constant([[[1,2,5],
                        [4,5,6]],
                        [[6,7,8],
                         [9,4,6,]],
                         [[5,6,7],
                          [9,0,2]]])
 tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 5],
        [4, 5, 6]],

       [[6, 7, 8],
        [9, 4, 6]],

       [[5, 6, 7],
        [9, 0, 2]]], dtype=int32)>

#create random tensors

In [10]:
#create two random(same) tensors
rand_1 = tf.random.Generator.from_seed(42) #set seed for reproductivity
rand_1 = rand_1.normal(shape=(3,2))
rand_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
rand_1 = tf.random.Generator.from_seed(42) #set seed for reproductivity
rand_1 = rand_1.uniform(shape=(3,2))
rand_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [12]:
#shuffle tensors
not_shuffled = tf.constant([[10,4],
                            [3,6],
                           [2,7],
                           [8,9]])
not_shuffled

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  4],
       [ 3,  6],
       [ 2,  7],
       [ 8,  9]], dtype=int32)>

In [13]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 8,  9],
       [10,  4],
       [ 2,  7]], dtype=int32)>

#Tensors can be run on GPU

##turn numpy arrays into tensors

In [14]:
import numpy as np
numpy_A = np.arange(1,23, dtype=np.int32) #create and npy array in range 1-23
numpy_A
#X=tf.constant(some_matrix) #captital for matrix or tensor
#y=tf.constant(vector) #non-captial for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int32)

In [15]:
#create a rank 4 tensor(4 dim)
rank_4_tensor = tf.zeros(shape=[2,4,3,3])
rank_4_tensor

<tf.Tensor: shape=(2, 4, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

#Indexing tensors

In [16]:
#Get the first 2 elements of each dims
rank_4_tensor[:1, :1,:1,:2 ]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [17]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape ,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [18]:
#get last item of each row 
rank_2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#Add extra dims to array

In [19]:
rank_2_tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [20]:
rank_3_tensor =rank_2_tensor[..., tf.newaxis]
rank_3_tensor.shape

TensorShape([2, 2, 1])

In [21]:
tf.expand_dims(rank_2_tensor, axis=-1) #expand last axis(2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [22]:
tf.expand_dims(rank_2_tensor, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [23]:
tf.expand_dims(rank_2_tensor, axis=1) 

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

#Tensor operations

In [24]:
#addition
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [25]:
#matrix multiplication
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [27]:
#matrix multipllication with python operator @
tensor@tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [28]:
X=tf.constant([[10,7],[3,4],[5,6]])
Y=tf.constant([[7,8],[9,10],[11,12]])

In [30]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [31]:
X.shape , Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [32]:
#since size-incompatible, we need to reshape them
#change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [33]:
X@tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[140, 157, 174],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

#Aggregating tensors

In [34]:
#get the absolute value
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [35]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [36]:
E= tf.constant(np.random.randint(0,100,size=50))
E 

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 49, 44, 42, 73,  9,  2, 21, 33, 74, 69, 56, 25, 75, 42, 43, 71,
       35, 27, 75, 77, 80, 48,  0, 44, 89, 48, 81, 85, 93, 56, 21, 71, 64,
       56, 44, 74, 39, 44, 44, 70, 21,  5, 65, 38,  7,  7,  2, 93, 58])>

#find positional min or max

In [41]:
 #create a tensor and find positions of min,max of a tensor
tf.random.set_seed(42)
 F = tf.random.uniform(shape=[50])
 F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
 #position of max val
 tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [44]:
#value of it
F[ tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [45]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

#Squaring, log, square root

In [49]:
#create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [50]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [53]:
  tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>