In [7]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np 


In [8]:
df = pd.read_csv('dataSet.csv')

In [9]:
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [10]:
Array_dataset = df.values

In [11]:
Array_dataset

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 0.000e+00,
        3.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        3.000e+00]])

In [12]:
X = Array_dataset[:,0:20]
Y = Array_dataset[:,20]

In [13]:
# transform data 
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [14]:
X_scale

array([[0.22778891, 0.        , 0.68      , ..., 0.        , 0.        ,
        1.        ],
       [0.34736139, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.04141617, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.94188377, 0.        , 0.16      , ..., 1.        , 1.        ,
        0.        ],
       [0.6753507 , 0.        , 0.16      , ..., 1.        , 1.        ,
        1.        ],
       [0.00601202, 1.        , 0.6       , ..., 1.        , 1.        ,
        1.        ]])

In [15]:
Y = df['price_range']

In [16]:
Y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [ ]:
#splitting data into train,validate and testing sets 

In [17]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.2 , random_state=42)

In [18]:
X_val_and_test

array([[0.76486306, 0.        , 0.8       , ..., 1.        , 1.        ,
        0.        ],
       [0.45490982, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.98263193, 0.        , 0.96      , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.36272545, 0.        , 0.52      , ..., 1.        , 1.        ,
        1.        ],
       [0.15163661, 0.        , 0.88      , ..., 1.        , 1.        ,
        1.        ],
       [0.45691383, 0.        , 0.56      , ..., 1.        , 1.        ,
        1.        ]])

In [19]:
# split for validate and test
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [20]:
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(1600, 20) (200, 20) (200, 20) (1600,) (200,) (200,)


In [21]:
#import keras 
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import SparseCategoricalCrossentropy
from keras.optimizers import Adam


In [22]:
# frame it to a sequential model
model = Sequential([
 Dense(16, activation="relu", input_shape=(20,)),
 Dense(16,activation='relu'),
 Dense(4,activation='softmax')
])

In [23]:
# configuration
model.compile(
   loss = SparseCategoricalCrossentropy(),
   optimizer = Adam(),
   metrics="accuracy")

In [24]:
model.fit(X_train,Y_train,validation_data=(X_val, Y_val),epochs=50)

Epoch 1/50
50/50 [==============================] - 1s 7ms/step - loss: 1.4259 - accuracy: 0.2431 - val_loss: 1.3819 - val_accuracy: 0.3000
Epoch 2/50
50/50 [==============================] - 0s 3ms/step - loss: 1.3678 - accuracy: 0.2906 - val_loss: 1.3501 - val_accuracy: 0.3400
Epoch 3/50
50/50 [==============================] - 0s 2ms/step - loss: 1.3225 - accuracy: 0.3431 - val_loss: 1.2954 - val_accuracy: 0.4150
Epoch 4/50
50/50 [==============================] - 0s 2ms/step - loss: 1.2466 - accuracy: 0.4200 - val_loss: 1.1852 - val_accuracy: 0.5450
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 1.1393 - accuracy: 0.5094 - val_loss: 1.0687 - val_accuracy: 0.5900
Epoch 6/50
50/50 [==============================] - 0s 2ms/step - loss: 1.0210 - accuracy: 0.5919 - val_loss: 0.9456 - val_accuracy: 0.6250
Epoch 7/50
50/50 [==============================] - 0s 2ms/step - loss: 0.9087 - accuracy: 0.6625 - val_loss: 0.8307 - val_accuracy: 0.7400
Epoch 8/50
50/50 [==

In [25]:
# summary of the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                336       
                                                                 
 dense_4 (Dense)             (None, 16)                272       
                                                                 
 dense_5 (Dense)             (None, 4)                 68        
                                                                 
Total params: 676
Trainable params: 676
Non-trainable params: 0
_________________________________________________________________


In [26]:
X_train.shape

(1600, 20)

In [27]:
# evaluation on test set
model.evaluate(X_test, Y_test)

7/7 [==============================] - 0s 2ms/step - loss: 0.1959 - accuracy: 0.9150


[0.19585706293582916, 0.9150000214576721]

In [28]:
# creates an array of predictions from a matrix of percentages of classifications
def predictionrelease(preds):
    arr=[]
    for i in range(0,len(preds)):
        ans=np.argmax(preds[i])
        arr.append(ans)
    len(arr)
    return arr

In [29]:
#testing our cross val sets
prediction_Y = model.predict(X_test)
testing_preds = predictionrelease(prediction_Y)

7/7 [==============================] - 0s 1ms/step


In [30]:
# check accuracy and generate clssification report

In [31]:
from sklearn.metrics import classification_report,confusion_matrix

#cross validation
print(classification_report(Y_test,testing_preds)) 

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        47
           1       0.85      1.00      0.92        50
           2       0.93      0.78      0.85        51
           3       0.91      0.94      0.92        52

    accuracy                           0.92       200
   macro avg       0.92      0.92      0.92       200
weighted avg       0.92      0.92      0.91       200

